Feature/issue 23/profile security questions
DiegoE-prog/Blue-Cross-JCE-2021 pull request #10
Opened 2023-10-25 22:56 UTC by MauricioJChavez

Added security questions section to profile

2023-10-25 23:37 UTC, AdrianSalas1992 approved these changes, later dismissed
good

2023-10-26 17:19 UTC, DiegoE-prog requested changes
Everything is okay. You just forgot to add a button at the bottom.

2023-10-26 17:53 UTC, AdrianSalas1992 approved these changes

2023-10-26 22:18 UTC, DiegoE-prog approved these changes

2023-10-26 23:19 UTC, merged