member, payor and provider fill
DiegoE-prog/Blue-Cross-JCE-2021 pull request #35
Opened 2023-11-10 22:20 UTC by AdrianSalas1992

2023-11-10 22:55 UTC, JAMendozaSa requested changes
You have some erros please, please check

2023-11-10 22:55 UTC, JAMendozaSa commented on frontend/jce-app/src/api/payorapi.js
> -	const response = await axios.get(`${apiroutes.BASEROUTE}/api/payor/GetList`)
Don't change the route, because you can changen something the others fix

2023-11-10 22:55 UTC, JAMendozaSa commented on src/JCE.API/appsettings.Development.json
Same error

2023-11-10 22:55 UTC, JAMendozaSa commented on src/JCE.Data/Data/Migrations/CreatePayors.cs
> +[Migration(101120231234)]
Why do you change this, if you change this on production we have future problems

2023-11-10 23:13 UTC, MauricioJChavez commented on frontend/jce-app/src/views/Claims/ClaimPage.js
> +	},[])
You can include all of the functions (fetchMember, fetchPayor and fetchProvider) inside the same useEffect
(Not required, but can improve the code)

2023-11-10 23:16 UTC, MauricioJChavez requested changes
Check the errors left by Juan and Diego, everything else seems to be ok
Also, the change I suggested could be a good addition, but is not completley necessary

2023-11-13 20:30 UTC, JAMendozaSa requested changes
same error please check

2023-11-13 20:30 UTC, JAMendozaSa commented on frontend/jce-app/src/api/payorapi.js
same error

2023-11-14 18:37 UTC, JAMendozaSa requested changes
Same error
You need to change getlisto to GetList please

2023-11-14 19:49 UTC, JAMendozaSa approved these changes
Approve

2023-11-14 20:36 UTC, MauricioJChavez approved these changes
Looks good

2023-11-14 21:58 UTC, merged